/**
 * 11 AVATAR DIGITAL HUB - GST Integration Module
 * Enterprise-grade GST compliance & taxation system
 * GSTN API, E-invoicing, E-way bills, HSN/SAC codes, ITC reconciliation, return filing
 * 
 * @module GSTIntegration
 * @version 2.0.0
 * @author 11 Avatar Digital Hub
 * @license GPL-3.0
 */

import { EventBus } from '../core/eventBus.js';
import { State } from '../core/state.js';
import { API } from '../core/api.js';
import { Cache } from '../core/cache.js';
import { Permissions } from '../auth/permissions.js';
import { Formatters } from '../utils/formatters.js';
import { Validators } from '../utils/validators.js';
import { Modal } from '../components/modal.js';
import { Toast } from '../components/toast.js';

/**
 * GST Integration - Complete GST compliance management
 * GSTN API, E-invoicing, E-way bill, HSN codes, ITC, returns
 */
class GSTIntegration {
    constructor() {
        this.moduleName = 'gst';
        this.apiEndpoint = '/api/gst';
        this.cachePrefix = 'gst_';
        this.cacheTimeout = 30 * 60 * 1000;

        this.gstTypes = {
            'cgst': { label: 'CGST', fullForm: 'Central GST', rate: 9, authority: 'Central Government' },
            'sgst': { label: 'SGST', fullForm: 'State GST', rate: 9, authority: 'State Government' },
            'igst': { label: 'IGST', fullForm: 'Integrated GST', rate: 18, authority: 'Central Government' },
            'utgst': { label: 'UTGST', fullForm: 'Union Territory GST', rate: 9, authority: 'UT Government' },
            'cess': { label: 'Cess', fullForm: 'Compensation Cess', rate: 0, authority: 'Central Government' }
        };

        this.gstRates = {
            '0%': { rate: 0, label: 'Nil Rated', items: ['fresh vegetables', 'bread', 'salt', 'books'] },
            '5%': { rate: 5, label: '5% Slab', items: ['packaged food', 'tea', 'coffee', 'spices'] },
            '12%': { rate: 12, label: '12% Slab', items: ['butter', 'ghee', 'mobiles', 'computers'] },
            '18%': { rate: 18, label: '18% Slab', items: ['IT services', 'consulting', 'software'] },
            '28%': { rate: 28, label: '28% Slab', items: ['luxury cars', 'tobacco', 'aerated drinks'] }
        };

        this.invoiceTypes = {
            'B2B': { label: 'B2B Invoice', requiresGSTIN: true, allowITC: true },
            'B2C': { label: 'B2C Invoice', requiresGSTIN: false, allowITC: false },
            'EXPORT': { label: 'Export Invoice', requiresGSTIN: true, allowITC: true, zeroRated: true },
            'SEZ': { label: 'SEZ Invoice', requiresGSTIN: true, allowITC: true, zeroRated: true },
            'DEEMED_EXPORT': { label: 'Deemed Export', requiresGSTIN: true, allowITC: true },
            'RCM': { label: 'Reverse Charge', requiresGSTIN: true, allowITC: true, rcmApplicable: true }
        };

        this.eInvoiceStatuses = {
            'draft': { label: 'Draft', color: '#6B7280' },
            'pending': { label: 'Pending Submission', color: '#F59E0B' },
            'submitted': { label: 'Submitted to IRP', color: '#3B82F6' },
            'generated': { label: 'IRN Generated', color: '#10B981' },
            'cancelled': { label: 'Cancelled', color: '#DC2626' },
            'failed': { label: 'Failed', color: '#991B1B' }
        };

        this.ewayBillStatuses = {
            'draft': { label: 'Draft', color: '#6B7280' },
            'generated': { label: 'Generated', color: '#3B82F6' },
            'active': { label: 'Active/In Transit', color: '#10B981' },
            'expired': { label: 'Expired', color: '#F97316' },
            'cancelled': { label: 'Cancelled', color: '#DC2626' }
        };

        this.returnTypes = {
            'GSTR1': { label: 'GSTR-1', description: 'Outward Supplies', frequency: 'monthly', dueDate: 11 },
            'GSTR2A': { label: 'GSTR-2A', description: 'Auto-drafted Inward Supplies', frequency: 'monthly', autoGenerated: true },
            'GSTR2B': { label: 'GSTR-2B', description: 'ITC Statement', frequency: 'monthly', autoGenerated: true },
            'GSTR3B': { label: 'GSTR-3B', description: 'Summary Return', frequency: 'monthly', dueDate: 20 },
            'GSTR4': { label: 'GSTR-4', description: 'Composition Dealer', frequency: 'annually', dueDate: 30 },
            'GSTR9': { label: 'GSTR-9', description: 'Annual Return', frequency: 'annually', dueDate: 31 },
            'GSTR9C': { label: 'GSTR-9C', description: 'Reconciliation Statement', frequency: 'annually' }
        };

        this.filingStatuses = {
            'not_filed': { label: 'Not Filed', color: '#6B7280', icon: 'fa-circle' },
            'draft': { label: 'Draft', color: '#F59E0B', icon: 'fa-pencil-alt' },
            'ready': { label: 'Ready to File', color: '#3B82F6', icon: 'fa-check' },
            'filed': { label: 'Filed', color: '#10B981', icon: 'fa-check-circle' },
            'late_filed': { label: 'Late Filed', color: '#F97316', icon: 'fa-exclamation-triangle' },
            'notice': { label: 'Notice Received', color: '#DC2626', icon: 'fa-exclamation-circle' }
        };

        this.gstinInfo = null;
        this.hsnCodes = new Map();
        this.sacCodes = new Map();
        this.eInvoices = new Map();
        this.ewayBills = new Map();
        this.returns = new Map();
        this.itcLedger = { cgst: 0, sgst: 0, igst: 0, cess: 0 };
        this.liabilityLedger = { cgst: 0, sgst: 0, igst: 0, cess: 0 };

        this.eInvoiceConfig = {
            enabled: true,
            autoGenerate: true,
            irpEndpoint: 'https://einvoice1.gst.gov.in',
            username: null,
            password: null,
            clientId: null,
            clientSecret: null,
            authToken: null,
            tokenExpiry: null
        };

        this.ewayBillConfig = {
            enabled: true,
            autoGenerate: false,
            threshold: 50000,
            portalEndpoint: 'https://ewaybillgst.gov.in',
            username: null,
            password: null,
            authToken: null
        };

        this.currentView = 'dashboard';
        this.selectedInvoiceId = null;
        this.selectedReturnId = null;

        this.pagination = { page: 1, limit: 25, total: 0, totalPages: 0 };

        this.metrics = {
            totalGSTInvoices: 0,
            totalEInvoices: 0,
            totalEWayBills: 0,
            totalTaxCollected: 0,
            totalITCClaimed: 0,
            netTaxPayable: 0,
            returnsFiled: 0,
            pendingReturns: 0,
            lastFilingDate: null,
            lastUpdated: null
        };

        this.elements = {
            container: null, dashboardView: null, invoiceList: null,
            einvoicePanel: null, ewayBillPanel: null, returnPanel: null,
            itcLedgerView: null, hsnLookup: null, filingStatus: null
        };

        this.init();
    }

    async init() {
        try {
            console.log('[GST] Initializing GST integration...');
            const canAccess = await Permissions.check('gst', 'read');
            if (!canAccess) { console.warn('[GST] Access denied'); return; }

            await this.loadGSTINInfo();
            await this.loadHSNCodes();
            await this.loadSACCodes();
            await this.loadEInvoices();
            await this.loadEWayBills();
            await this.loadReturns();
            await this.loadITCLedger();
            this.setupEventListeners();
            this.calculateMetrics();

            if (document.getElementById('gst-container')) await this.render();
            console.log('[GST] Initialized successfully');
            EventBus.emit('gst:ready', { metrics: this.metrics });
        } catch (error) {
            console.error('[GST] Initialization failed:', error);
        }
    }

    async loadGSTINInfo() {
        try {
            const response = await API.get(`${this.apiEndpoint}/gstin`);
            if (response.success && response.data) {
                this.gstinInfo = {
                    ...response.data,
                    isValid: response.data.status === 'active',
                    stateCode: response.data.gstin?.substring(0, 2),
                    panNumber: response.data.gstin?.substring(2, 12),
                    formattedGSTIN: this.formatGSTIN(response.data.gstin)
                };
            }
        } catch (error) { console.error('[GST] GSTIN load failed:', error); }
    }

    async loadHSNCodes() {
        try {
            const cached = await Cache.get(`${this.cachePrefix}hsn_codes`);
            if (cached && (Date.now() - cached.timestamp < 86400000)) {
                cached.data.forEach(hsn => this.hsnCodes.set(hsn.code, hsn));
                return;
            }
            const response = await API.get(`${this.apiEndpoint}/hsn-codes`);
            if (response.success && response.data) {
                this.hsnCodes.clear();
                response.data.forEach(hsn => this.hsnCodes.set(hsn.code, hsn));
                await Cache.set(`${this.cachePrefix}hsn_codes`, response.data, 86400000);
            }
        } catch (error) { console.error('[GST] HSN load failed:', error); }
    }

    async loadSACCodes() {
        try {
            const cached = await Cache.get(`${this.cachePrefix}sac_codes`);
            if (cached && (Date.now() - cached.timestamp < 86400000)) {
                cached.data.forEach(sac => this.sacCodes.set(sac.code, sac));
                return;
            }
            const response = await API.get(`${this.apiEndpoint}/sac-codes`);
            if (response.success && response.data) {
                this.sacCodes.clear();
                response.data.forEach(sac => this.sacCodes.set(sac.code, sac));
                await Cache.set(`${this.cachePrefix}sac_codes`, response.data, 86400000);
            }
        } catch (error) { console.error('[GST] SAC load failed:', error); }
    }

    async loadEInvoices() {
        try {
            const response = await API.get(`${this.apiEndpoint}/e-invoices`);
            if (response.success && response.data) {
                this.eInvoices.clear();
                response.data.forEach(inv => {
                    this.eInvoices.set(inv.id, {
                        ...inv,
                        formattedDate: Formatters.date(inv.invoiceDate),
                        formattedAmount: Formatters.currency(inv.totalAmount),
                        statusInfo: this.eInvoiceStatuses[inv.eInvoiceStatus] || this.eInvoiceStatuses.draft,
                        hasIRN: !!inv.irn,
                        hasQRCode: !!inv.qrCode,
                        isCancelled: inv.eInvoiceStatus === 'cancelled'
                    });
                });
                this.metrics.totalEInvoices = this.eInvoices.size;
            }
        } catch (error) { console.error('[GST] E-Invoices load failed:', error); }
    }

    async loadEWayBills() {
        try {
            const response = await API.get(`${this.apiEndpoint}/eway-bills`);
            if (response.success && response.data) {
                this.ewayBills.clear();
                response.data.forEach(bill => {
                    this.ewayBills.set(bill.id, {
                        ...bill,
                        formattedDate: Formatters.date(bill.generatedAt),
                        formattedValidUntil: Formatters.date(bill.validUntil),
                        statusInfo: this.ewayBillStatuses[bill.status] || this.ewayBillStatuses.draft,
                        isActive: bill.status === 'active',
                        isExpired: bill.status === 'expired',
                        distanceKm: bill.distance || 0,
                        vehicleInfo: bill.vehicleNumber || 'Not assigned'
                    });
                });
                this.metrics.totalEWayBills = this.ewayBills.size;
            }
        } catch (error) { console.error('[GST] E-Way Bills load failed:', error); }
    }

    async loadReturns() {
        try {
            const response = await API.get(`${this.apiEndpoint}/returns`);
            if (response.success && response.data) {
                this.returns.clear();
                response.data.forEach(ret => {
                    const returnType = this.returnTypes[ret.type];
                    const dueDate = returnType?.dueDate ? this.calculateDueDate(ret.period, returnType.dueDate) : null;
                    const isOverdue = dueDate && new Date() > dueDate && ret.status !== 'filed';
                    
                    this.returns.set(ret.id, {
                        ...ret,
                        returnTypeInfo: returnType,
                        dueDate: dueDate,
                        formattedDueDate: Formatters.date(dueDate),
                        formattedPeriod: this.formatPeriod(ret.period),
                        filingStatusInfo: this.filingStatuses[ret.filingStatus] || this.filingStatuses.not_filed,
                        isOverdue: isOverdue,
                        daysOverdue: isOverdue ? Math.ceil((new Date() - dueDate) / (1000 * 60 * 60 * 24)) : 0,
                        canFile: ret.filingStatus === 'ready' || ret.filingStatus === 'draft'
                    });
                });
                this.metrics.returnsFiled = Array.from(this.returns.values()).filter(r => r.filingStatus === 'filed').length;
                this.metrics.pendingReturns = Array.from(this.returns.values()).filter(r => r.isOverdue).length;
            }
        } catch (error) { console.error('[GST] Returns load failed:', error); }
    }

    async loadITCLedger() {
        try {
            const response = await API.get(`${this.apiEndpoint}/itc-ledger`);
            if (response.success && response.data) {
                this.itcLedger = { ...this.itcLedger, ...response.data.itc };
                this.liabilityLedger = { ...this.liabilityLedger, ...response.data.liability };
                this.metrics.totalITCClaimed = Object.values(this.itcLedger).reduce((a, b) => a + b, 0);
                this.metrics.netTaxPayable = Object.values(this.liabilityLedger).reduce((a, b) => a + b, 0) - this.metrics.totalITCClaimed;
            }
        } catch (error) { console.error('[GST] ITC Ledger load failed:', error); }
    }

    setupEventListeners() {
        EventBus.on('gst:calculate-tax', this.calculateGST.bind(this));
        EventBus.on('gst:generate-einvoice', this.generateEInvoice.bind(this));
        EventBus.on('gst:cancel-einvoice', this.cancelEInvoice.bind(this));
        EventBus.on('gst:generate-ewaybill', this.generateEWayBill.bind(this));
        EventBus.on('gst:update-ewaybill', this.updateEWayBill.bind(this));
        EventBus.on('gst:file-return', this.fileReturn.bind(this));
        EventBus.on('gst:reconcile-itc', this.reconcileITC.bind(this));
        EventBus.on('gst:validate-gstin', this.validateGSTIN.bind(this));
        EventBus.on('gst:lookup-hsn', this.lookupHSN.bind(this));
        EventBus.on('invoice:created', (invoice) => { if (this.eInvoiceConfig.autoGenerate && this.shouldGenerateEInvoice(invoice)) { this.generateEInvoice(invoice.id); } });
        console.log('[GST] Event listeners initialized');
    }

    calculateGST(invoiceData) {
        try {
            const { amount, gstRate, isInterState, placeOfSupply, billFromState } = invoiceData;
            const ratePercent = parseFloat(gstRate) || 18;
            const taxableAmount = parseFloat(amount) || 0;
            const gstAmount = taxableAmount * (ratePercent / 100);
            let cgst = 0, sgst = 0, igst = 0, utgst = 0, cess = 0;

            if (isInterState) {
                igst = gstAmount;
            } else {
                cgst = gstAmount / 2;
                sgst = gstAmount / 2;
                const isUT = ['32', '33', '34', '35', '36'].includes(placeOfSupply?.substring(0, 2));
                if (isUT) { utgst = sgst; sgst = 0; }
            }

            const totalGST = cgst + sgst + igst + utgst + cess;
            const totalAmount = taxableAmount + totalGST;

            return {
                taxableAmount: Math.round(taxableAmount * 100) / 100,
                gstRate: ratePercent,
                cgst: Math.round(cgst * 100) / 100,
                sgst: Math.round(sgst * 100) / 100,
                igst: Math.round(igst * 100) / 100,
                utgst: Math.round(utgst * 100) / 100,
                cess: Math.round(cess * 100) / 100,
                totalGST: Math.round(totalGST * 100) / 100,
                totalAmount: Math.round(totalAmount * 100) / 100,
                isInterState,
                hsnCode: invoiceData.hsnCode || null,
                sacCode: invoiceData.sacCode || null,
                placeOfSupply,
                billFromState
            };
        } catch (error) {
            console.error('[GST] Tax calculation failed:', error);
            return null;
        }
    }

    async generateEInvoice(invoiceId) {
        try {
            const invoice = await API.get(`/api/invoices/${invoiceId}`);
            if (!invoice.success) throw new Error('Invoice not found');
            if (!this.shouldGenerateEInvoice(invoice.data)) throw new Error('Invoice does not meet E-Invoice criteria');

            const gstCalculation = this.calculateGST({
                amount: invoice.data.subtotal,
                gstRate: invoice.data.gstRate || 18,
                isInterState: invoice.data.gstDetails?.isInterState || false,
                placeOfSupply: invoice.data.placeOfSupply,
                billFromState: this.gstinInfo?.stateCode
            });

            const einvoicePayload = this.buildEInvoicePayload(invoice.data, gstCalculation);
            const irpToken = await this.authenticateIRP();
            const response = await fetch(`${this.eInvoiceConfig.irpEndpoint}/invoice`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${irpToken}`, 'Content-Type': 'application/json' },
                body: JSON.stringify(einvoicePayload)
            });

            if (!response.ok) throw new Error(`IRP submission failed: ${response.status}`);
            const irpResponse = await response.json();
            const einvoiceData = {
                id: `einv-${invoiceId}`,
                invoiceId: invoiceId,
                irn: irpResponse.Irn,
                ackNo: irpResponse.AckNo,
                ackDate: irpResponse.AckDt,
                qrCode: irpResponse.SignedQRCode,
                status: 'generated',
                generatedAt: new Date().toISOString()
            };

            await API.post(`${this.apiEndpoint}/e-invoices`, einvoiceData);
            this.eInvoices.set(einvoiceData.id, { ...einvoiceData, formattedDate: Formatters.date(einvoiceData.generatedAt), statusInfo: this.eInvoiceStatuses.generated, hasIRN: true, hasQRCode: true });
            this.metrics.totalEInvoices++;

            Toast.show('E-Invoice generated successfully', 'success');
            EventBus.emit('gst:einvoice-generated', einvoiceData);
            return einvoiceData;
        } catch (error) {
            console.error('[GST] E-Invoice generation failed:', error);
            Toast.show('E-Invoice generation failed: ' + error.message, 'error');
            return null;
        }
    }

    shouldGenerateEInvoice(invoice) {
        if (!this.eInvoiceConfig.enabled) return false;
        if (invoice.invoiceType === 'B2C') return false;
        if (invoice.totalAmount < 50000) return false;
        if (invoice.eInvoiceStatus === 'generated') return false;
        return true;
    }

    buildEInvoicePayload(invoice, gstCalc) {
        return {
            Version: '1.1',
            TranDtls: { TaxSch: 'GST', SupTyp: invoice.invoiceType || 'B2B', RegRev: 'N', EcmGstin: null, IgstOnIntra: 'N' },
            DocDtls: { Typ: 'INV', No: invoice.invoiceNumber, Dt: invoice.invoiceDate },
            SellerDtls: { Gstin: this.gstinInfo?.gstin, LglNm: this.gstinInfo?.legalName, TrdNm: this.gstinInfo?.tradeName, Addr1: this.gstinInfo?.address?.line1, Loc: this.gstinInfo?.address?.city, Pin: this.gstinInfo?.address?.pincode, Stcd: this.gstinInfo?.stateCode, Ph: this.gstinInfo?.phone, Em: this.gstinInfo?.email },
            BuyerDtls: { Gstin: invoice.clientGST, LglNm: invoice.clientName, TrdNm: invoice.clientCompany || invoice.clientName, Pos: invoice.placeOfSupply?.substring(0, 2) || '27', Addr1: invoice.clientAddress?.line1, Loc: invoice.clientAddress?.city, Pin: invoice.clientAddress?.pincode, Stcd: invoice.clientAddress?.state?.substring(0, 2) || '27' },
            ItemList: (invoice.items || []).map(item => ({
                SlNo: item.srNo || '1',
                PrdDesc: item.description,
                IsServc: item.sacCode ? 'Y' : 'N',
                HsnCd: item.hsnSac || item.hsnCode || '998311',
                Qty: item.quantity || 1,
                Unit: item.unit || 'NOS',
                UnitPrice: item.rate || 0,
                TotAmt: item.amount || 0,
                Discount: 0,
                PreTaxVal: item.amount || 0,
                AssAmt: item.amount || 0,
                GstRt: item.gstRate || 18,
                IgstAmt: gstCalc.igst || 0,
                CgstAmt: gstCalc.cgst || 0,
                SgstAmt: gstCalc.sgst || 0,
                CesRt: 0,
                CesAmt: 0,
                CesNonAdvlAmt: 0,
                StateCesRt: 0,
                StateCesAmt: 0,
                StateCesNonAdvlAmt: 0,
                OthChrg: 0,
                TotItemVal: (item.amount || 0) + (gstCalc.igst || 0) + (gstCalc.cgst || 0) + (gstCalc.sgst || 0)
            })),
            ValDtls: {
                AssVal: gstCalc.taxableAmount,
                CgstVal: gstCalc.cgst,
                SgstVal: gstCalc.sgst,
                IgstVal: gstCalc.igst,
                CesVal: 0,
                StCesVal: 0,
                Discount: 0,
                OthChrg: 0,
                RndOffAmt: 0,
                TotInvVal: gstCalc.totalAmount,
                TotInvValFc: gstCalc.totalAmount
            }
        };
    }

    async authenticateIRP() {
        try {
            if (this.eInvoiceConfig.authToken && this.eInvoiceConfig.tokenExpiry && new Date() < new Date(this.eInvoiceConfig.tokenExpiry)) {
                return this.eInvoiceConfig.authToken;
            }
            const response = await API.post(`${this.apiEndpoint}/irp/auth`, {
                username: this.eInvoiceConfig.username,
                password: this.eInvoiceConfig.password,
                clientId: this.eInvoiceConfig.clientId,
                clientSecret: this.eInvoiceConfig.clientSecret
            });
            if (response.success) {
                this.eInvoiceConfig.authToken = response.data.token;
                this.eInvoiceConfig.tokenExpiry = response.data.expiry;
                return response.data.token;
            }
            throw new Error('IRP authentication failed');
        } catch (error) {
            console.error('[GST] IRP auth failed:', error);
            throw error;
        }
    }

    async cancelEInvoice(invoiceId, reason) {
        try {
            const einvoice = this.eInvoices.get(`einv-${invoiceId}`);
            if (!einvoice) throw new Error('E-Invoice not found');
            const irpToken = await this.authenticateIRP();
            const response = await fetch(`${this.eInvoiceConfig.irpEndpoint}/invoice/cancel`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${irpToken}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({ Irn: einvoice.irn, CnlRsn: reason || 'Duplicate', CnlRem: reason || 'Cancelled by user' })
            });
            if (!response.ok) throw new Error(`IRP cancellation failed: ${response.status}`);
            einvoice.status = 'cancelled';
            einvoice.statusInfo = this.eInvoiceStatuses.cancelled;
            einvoice.cancelledAt = new Date().toISOString();
            einvoice.cancelReason = reason;
            this.eInvoices.set(`einv-${invoiceId}`, einvoice);
            await API.put(`${this.apiEndpoint}/e-invoices/${invoiceId}/cancel`, { reason });
            Toast.show('E-Invoice cancelled successfully', 'success');
            return einvoice;
        } catch (error) {
            console.error('[GST] E-Invoice cancellation failed:', error);
            Toast.show('Cancellation failed: ' + error.message, 'error');
            return null;
        }
    }

    async generateEWayBill(invoiceId, transportDetails) {
        try {
            const invoice = this.eInvoices.get(`einv-${invoiceId}`) || (await API.get(`/api/invoices/${invoiceId}`)).data;
            if (!invoice) throw new Error('Invoice not found');
            const totalAmount = invoice.totalAmount || invoice.total;
            if (totalAmount < this.ewayBillConfig.threshold) throw new Error(`Amount below E-Way Bill threshold (₹${this.ewayBillConfig.threshold})`);

            const ewayBillPayload = {
                supplyType: invoice.invoiceType === 'EXPORT' ? 'EXP' : invoice.gstDetails?.isInterState ? 'INTER' : 'INTRA',
                subSupplyType: invoice.invoiceType || 'B2B',
                docType: 'INV',
                docNo: invoice.invoiceNumber || invoice.docNo,
                docDate: invoice.invoiceDate,
                fromGstin: this.gstinInfo?.gstin,
                fromPlace: this.gstinInfo?.address?.city || '',
                fromState: parseInt(this.gstinInfo?.stateCode) || 27,
                toGstin: invoice.clientGST || 'URP',
                toPlace: invoice.clientAddress?.city || '',
                toState: parseInt(invoice.placeOfSupply?.substring(0, 2)) || 27,
                totalValue: totalAmount,
                cgstValue: invoice.gstDetails?.cgst || 0,
                sgstValue: invoice.gstDetails?.sgst || 0,
                igstValue: invoice.gstDetails?.igst || 0,
                cessValue: 0,
                transporterId: transportDetails?.transporterId || '',
                transporterName: transportDetails?.transporterName || '',
                vehicleNumber: transportDetails?.vehicleNumber || '',
                distance: transportDetails?.distance || 0,
                validUntil: transportDetails?.validUntil || new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString()
            };

            const response = await API.post(`${this.apiEndpoint}/eway-bills`, ewayBillPayload);
            if (!response.success) throw new Error(response.error);

            const ewayBillData = { ...response.data, formattedDate: Formatters.date(new Date()), formattedValidUntil: Formatters.date(response.data.validUntil), statusInfo: this.ewayBillStatuses.generated, isActive: true, isExpired: false };
            this.ewayBills.set(ewayBillData.id, ewayBillData);
            this.metrics.totalEWayBills++;

            Toast.show('E-Way Bill generated successfully', 'success');
            EventBus.emit('gst:ewaybill-generated', ewayBillData);
            return ewayBillData;
        } catch (error) {
            console.error('[GST] E-Way Bill generation failed:', error);
            Toast.show('E-Way Bill failed: ' + error.message, 'error');
            return null;
        }
    }

    async updateEWayBill(ewayBillId, updates) {
        try {
            const response = await API.put(`${this.apiEndpoint}/eway-bills/${ewayBillId}`, updates);
            if (!response.success) throw new Error(response.error);
            const bill = this.ewayBills.get(ewayBillId);
            if (bill) Object.assign(bill, response.data);
            Toast.show('E-Way Bill updated', 'success');
            return response.data;
        } catch (error) {
            console.error('[GST] E-Way Bill update failed:', error);
            return null;
        }
    }

    async fileReturn(returnId) {
        try {
            const returnData = this.returns.get(returnId);
            if (!returnData) throw new Error('Return not found');
            if (!returnData.canFile) throw new Error('Return cannot be filed in current status');

            const confirmed = await this.confirmDialog('File Return', `File ${returnData.returnTypeInfo?.label} for period ${returnData.formattedPeriod}?`);
            if (!confirmed) return;

            const response = await API.post(`${this.apiEndpoint}/returns/${returnId}/file`);
            if (!response.success) throw new Error(response.error);

            returnData.filingStatus = 'filed';
            returnData.filingStatusInfo = this.filingStatuses.filed;
            returnData.filedAt = new Date().toISOString();
            returnData.acknowledgementNo = response.data.ackNo;
            this.returns.set(returnId, returnData);
            this.metrics.returnsFiled++;
            this.metrics.lastFilingDate = new Date();

            Toast.show('Return filed successfully', 'success');
            EventBus.emit('gst:return-filed', { returnId, ackNo: response.data.ackNo });
            return response.data;
        } catch (error) {
            console.error('[GST] Return filing failed:', error);
            Toast.show('Filing failed: ' + error.message, 'error');
            return null;
        }
    }

    async reconcileITC(period) {
        try {
            Toast.show('Reconciling ITC...', 'info');
            const response = await API.post(`${this.apiEndpoint}/reconcile-itc`, { period });
            if (!response.success) throw new Error(response.error);

            this.itcLedger = { ...this.itcLedger, ...response.data.reconciledITC };
            const matched = response.data.matched || 0;
            const mismatched = response.data.mismatched || 0;

            if (mismatched > 0) {
                Toast.show(`Reconciliation: ${matched} matched, ${mismatched} mismatched`, 'warning');
            } else {
                Toast.show(`ITC reconciled: ${matched} invoices matched`, 'success');
            }

            EventBus.emit('gst:itc-reconciled', response.data);
            return response.data;
        } catch (error) {
            console.error('[GST] ITC reconciliation failed:', error);
            Toast.show('Reconciliation failed', 'error');
            return null;
        }
    }

    async validateGSTIN(gstin) {
        try {
            const cleaned = gstin?.replace(/\s/g, '').toUpperCase() || '';
            if (cleaned.length !== 15) return { valid: false, error: 'GSTIN must be 15 characters' };
            const gstinRegex = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;
            if (!gstinRegex.test(cleaned)) return { valid: false, error: 'Invalid GSTIN format' };
            const response = await API.get(`${this.apiEndpoint}/validate-gstin/${cleaned}`);
            if (response.success) return { valid: true, data: response.data };
            return { valid: false, error: response.error || 'Validation failed' };
        } catch (error) {
            console.error('[GST] GSTIN validation failed:', error);
            return { valid: false, error: 'Validation service unavailable' };
        }
    }

    async lookupHSN(query) {
        try {
            if (!query || query.length < 2) return [];
            const results = [];
            this.hsnCodes.forEach((hsn, code) => {
                if (code.includes(query) || hsn.description?.toLowerCase().includes(query.toLowerCase())) {
                    results.push({ code, ...hsn });
                }
            });
            return results.slice(0, 20);
        } catch (error) { console.error('[GST] HSN lookup failed:', error); return []; }
    }

    formatGSTIN(gstin) {
        if (!gstin || gstin.length !== 15) return gstin;
        return `${gstin.substring(0, 2)} ${gstin.substring(2, 7)} ${gstin.substring(7, 11)} ${gstin.substring(11, 12)} ${gstin.substring(12)}`;
    }

    formatPeriod(period) {
        if (!period) return '';
        const [year, month] = period.split('-');
        const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        return month ? `${monthNames[parseInt(month) - 1]} ${year}` : period;
    }

    calculateDueDate(period, dueDay) {
        if (!period || !dueDay) return null;
        const [year, month] = period.split('-').map(Number);
        return new Date(year, month, dueDay);
    }

    async render(container = null) {
        try {
            const targetContainer = container || document.getElementById('gst-container');
            if (!targetContainer) return;

            const html = `
                <div class="gst-container">
                    <div class="gst-header">
                        <h3><i class="fas fa-file-invoice"></i> GST Compliance</h3>
                        <div class="gstin-display">
                            <span>GSTIN: <strong>${this.gstinInfo?.formattedGSTIN || 'Not configured'}</strong></span>
                            <span class="status-badge ${this.gstinInfo?.isValid ? 'active' : 'inactive'}">${this.gstinInfo?.isValid ? 'Active' : 'Inactive'}</span>
                        </div>
                    </div>

                    <div class="gst-metrics-dashboard">
                        <div class="metric-card"><i class="fas fa-file-invoice"></i><span class="value">${this.metrics.totalEInvoices}</span><span class="label">E-Invoices</span></div>
                        <div class="metric-card"><i class="fas fa-truck"></i><span class="value">${this.metrics.totalEWayBills}</span><span class="label">E-Way Bills</span></div>
                        <div class="metric-card"><i class="fas fa-rupee-sign"></i><span class="value">${Formatters.currency(this.metrics.totalTaxCollected)}</span><span class="label">Tax Collected</span></div>
                        <div class="metric-card"><i class="fas fa-receipt"></i><span class="value">${Formatters.currency(this.metrics.totalITCClaimed)}</span><span class="label">ITC Claimed</span></div>
                        <div class="metric-card"><i class="fas fa-balance-scale"></i><span class="value">${Formatters.currency(this.metrics.netTaxPayable)}</span><span class="label">Net Payable</span></div>
                        <div class="metric-card"><i class="fas fa-check-circle"></i><span class="value">${this.metrics.returnsFiled}</span><span class="label">Returns Filed</span></div>
                    </div>

                    <div class="gst-tabs">
                        <button class="tab-btn ${this.currentView === 'dashboard' ? 'active' : ''}" onclick="window.Global.GST.switchView('dashboard')"><i class="fas fa-chart-pie"></i> Dashboard</button>
                        <button class="tab-btn ${this.currentView === 'einvoice' ? 'active' : ''}" onclick="window.Global.GST.switchView('einvoice')"><i class="fas fa-file-invoice"></i> E-Invoices</button>
                        <button class="tab-btn ${this.currentView === 'ewaybill' ? 'active' : ''}" onclick="window.Global.GST.switchView('ewaybill')"><i class="fas fa-truck"></i> E-Way Bills</button>
                        <button class="tab-btn ${this.currentView === 'returns' ? 'active' : ''}" onclick="window.Global.GST.switchView('returns')"><i class="fas fa-clipboard-check"></i> Returns</button>
                        <button class="tab-btn ${this.currentView === 'itc' ? 'active' : ''}" onclick="window.Global.GST.switchView('itc')"><i class="fas fa-calculator"></i> ITC Ledger</button>
                    </div>

                    <div class="gst-content">${this.renderCurrentView()}</div>
                </div>
            `;

            targetContainer.innerHTML = html;
            console.log('[GST] UI rendered');
        } catch (error) { console.error('[GST] Render failed:', error); }
    }

    renderCurrentView() {
        switch (this.currentView) {
            case 'einvoice': return this.renderEInvoiceView();
            case 'ewaybill': return this.renderEWayBillView();
            case 'returns': return this.renderReturnsView();
            case 'itc': return this.renderITCView();
            default: return this.renderDashboardView();
        }
    }

    renderDashboardView() {
        return `
            <div class="gst-dashboard">
                <div class="dashboard-section">
                    <h4><i class="fas fa-exclamation-circle"></i> Pending Actions</h4>
                    <div class="pending-actions">
                        ${this.metrics.pendingReturns > 0 ? `<div class="action-alert danger"><i class="fas fa-exclamation-triangle"></i><span>${this.metrics.pendingReturns} returns overdue</span><button class="btn btn-sm btn-danger" onclick="window.Global.GST.switchView('returns')">File Now</button></div>` : ''}
                        ${this.metrics.netTaxPayable > 0 ? `<div class="action-alert warning"><i class="fas fa-rupee-sign"></i><span>Net tax payable: ${Formatters.currency(this.metrics.netTaxPayable)}</span></div>` : ''}
                    </div>
                </div>
                <div class="dashboard-section">
                    <h4><i class="fas fa-clock"></i> Upcoming Due Dates</h4>
                    <div class="due-dates-list">${this.renderUpcomingDueDates()}</div>
                </div>
            </div>
        `;
    }

    renderEInvoiceView() {
        return `
            <div class="einvoice-view">
                <div class="view-header">
                    <h4>E-Invoices</h4>
                    <button class="btn btn-primary" onclick="window.Global.GST.generateEInvoice(prompt('Enter Invoice ID:'))"><i class="fas fa-plus"></i> Generate E-Invoice</button>
                </div>
                <table class="gst-table">
                    <thead><tr><th>IRN</th><th>Invoice #</th><th>Date</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead>
                    <tbody>${Array.from(this.eInvoices.values()).map(inv => `
                        <tr>
                            <td>${inv.irn ? `<code>${inv.irn.substring(0, 16)}...</code>` : '-'}</td>
                            <td>${this.escapeHtml(inv.invoiceId)}</td>
                            <td>${inv.formattedDate}</td>
                            <td>${inv.formattedAmount}</td>
                            <td><span class="status-badge" style="background:${inv.statusInfo.color}20;color:${inv.statusInfo.color}">${inv.statusInfo.label}</span></td>
                            <td>${!inv.isCancelled ? `<button class="btn btn-sm btn-danger" onclick="window.Global.GST.cancelEInvoice('${inv.invoiceId}')">Cancel</button>` : ''}</td>
                        </tr>
                    `).join('') || '<tr><td colspan="6">No E-Invoices</td></tr>'}</tbody>
                </table>
            </div>
        `;
    }

    renderEWayBillView() {
        return `
            <div class="ewaybill-view">
                <div class="view-header"><h4>E-Way Bills</h4></div>
                <table class="gst-table">
                    <thead><tr><th>E-Way Bill #</th><th>Invoice</th><th>Generated</th><th>Valid Until</th><th>Vehicle</th><th>Distance</th><th>Status</th></tr></thead>
                    <tbody>${Array.from(this.ewayBills.values()).map(bill => `
                        <tr>
                            <td><code>${this.escapeHtml(bill.ewayBillNumber || bill.id)}</code></td>
                            <td>${this.escapeHtml(bill.invoiceNumber || bill.invoiceId)}</td>
                            <td>${bill.formattedDate}</td>
                            <td>${bill.formattedValidUntil}</td>
                            <td>${bill.vehicleInfo}</td>
                            <td>${bill.distanceKm} km</td>
                            <td><span class="status-badge" style="background:${bill.statusInfo.color}20;color:${bill.statusInfo.color}">${bill.statusInfo.label}</span></td>
                        </tr>
                    `).join('') || '<tr><td colspan="7">No E-Way Bills</td></tr>'}</tbody>
                </table>
            </div>
        `;
    }

    renderReturnsView() {
        return `
            <div class="returns-view">
                <div class="view-header"><h4>GST Returns</h4></div>
                <table class="gst-table">
                    <thead><tr><th>Return Type</th><th>Period</th><th>Due Date</th><th>Status</th><th>Actions</th></tr></thead>
                    <tbody>${Array.from(this.returns.values()).map(ret => `
                        <tr class="${ret.isOverdue ? 'overdue-row' : ''}">
                            <td><strong>${ret.returnTypeInfo?.label}</strong><br><small>${ret.returnTypeInfo?.description}</small></td>
                            <td>${ret.formattedPeriod}</td>
                            <td>${ret.formattedDueDate}${ret.isOverdue ? `<span class="overdue-tag">${ret.daysOverdue}d overdue</span>` : ''}</td>
                            <td><span class="status-badge" style="background:${ret.filingStatusInfo.color}20;color:${ret.filingStatusInfo.color}">${ret.filingStatusInfo.label}</span></td>
                            <td>${ret.canFile ? `<button class="btn btn-sm btn-primary" onclick="window.Global.GST.fileReturn('${ret.id}')">File Now</button>` : ''}</td>
                        </tr>
                    `).join('') || '<tr><td colspan="5">No returns found</td></tr>'}</tbody>
                </table>
            </div>
        `;
    }

    renderITCView() {
        return `
            <div class="itc-view">
                <div class="view-header"><h4>Input Tax Credit Ledger</h4></div>
                <div class="itc-summary">
                    <div class="itc-card"><h5>CGST</h5><span>${Formatters.currency(this.itcLedger.cgst)}</span></div>
                    <div class="itc-card"><h5>SGST</h5><span>${Formatters.currency(this.itcLedger.sgst)}</span></div>
                    <div class="itc-card"><h5>IGST</h5><span>${Formatters.currency(this.itcLedger.igst)}</span></div>
                    <div class="itc-card"><h5>Cess</h5><span>${Formatters.currency(this.itcLedger.cess)}</span></div>
                </div>
                <div class="itc-total"><strong>Total ITC Available: ${Formatters.currency(Object.values(this.itcLedger).reduce((a, b) => a + b, 0))}</strong></div>
                <button class="btn btn-primary" onclick="window.Global.GST.reconcileITC(prompt('Enter period (YYYY-MM):'))"><i class="fas fa-sync"></i> Reconcile ITC</button>
            </div>
        `;
    }

    renderUpcomingDueDates() {
        const upcoming = Array.from(this.returns.values()).filter(r => r.filingStatus !== 'filed' && r.dueDate).sort((a, b) => a.dueDate - b.dueDate).slice(0, 5);
        if (upcoming.length === 0) return '<p>No upcoming due dates</p>';
        return upcoming.map(ret => `
            <div class="due-date-item ${ret.isOverdue ? 'overdue' : ''}">
                <span><strong>${ret.returnTypeInfo?.label}</strong> - ${ret.formattedPeriod}</span>
                <span>Due: ${ret.formattedDueDate}</span>
                <span class="status-badge" style="background:${ret.filingStatusInfo.color}20;color:${ret.filingStatusInfo.color}">${ret.filingStatusInfo.label}</span>
            </div>
        `).join('');
    }

    async switchView(view) {
        this.currentView = view;
        await this.render();
    }

    calculateMetrics() {
        let totalTaxCollected = 0;
        this.eInvoices.forEach(inv => { totalTaxCollected += (inv.totalGST || 0); });
        this.metrics.totalTaxCollected = totalTaxCollected;
        this.metrics.lastUpdated = new Date();
    }

    confirmDialog(title, message) {
        return new Promise((resolve) => {
            const modal = new Modal({ title, content: `<p>${message}</p><div class="modal-actions"><button class="btn btn-secondary cancel-btn">Cancel</button><button class="btn btn-primary confirm-btn">Confirm</button></div>`, size: 'small', onClose: () => resolve(false) });
            modal.open();
            setTimeout(() => {
                document.querySelector('.cancel-btn')?.addEventListener('click', () => { modal.close(); resolve(false); });
                document.querySelector('.confirm-btn')?.addEventListener('click', () => { modal.close(); resolve(true); });
            }, 100);
        });
    }

    escapeHtml(text) {
        if (!text) return '';
        const div = document.createElement('div');
        div.textContent = text;
        return div.innerHTML;
    }

    destroy() {
        EventBus.off('gst:calculate-tax');
        EventBus.off('gst:generate-einvoice');
        EventBus.off('gst:cancel-einvoice');
        EventBus.off('gst:generate-ewaybill');
        EventBus.off('gst:update-ewaybill');
        EventBus.off('gst:file-return');
        EventBus.off('gst:reconcile-itc');
        console.log('[GST] Module destroyed');
    }
}

const gstIntegration = new GSTIntegration();
export { gstIntegration, GSTIntegration };
export default gstIntegration;

if (typeof window !== 'undefined') {
    window.Global = window.Global || {};
    window.Global.GST = gstIntegration;
}
